-- Update passwords and salts (crypto.scrypt with random salts)
-- Generated by generate_passwords.mjs

-- Teachers (password: password123)
UPDATE users SET password='775e1e48673344641373706d26f6d739', salt='d6cfec251b02b5ce' WHERE email='mario.rossi@polito.it';
UPDATE users SET password='16f70a414a20313bbd5b87d2513b1de0', salt='825d959d8180174f' WHERE email='anna.verdi@polito.it';

-- Students (password: student123)
UPDATE users SET password='04a4922c4a0fe5754ce8c8afee4060ec', salt='efb116c4eec7e7a2' WHERE email='giulia.bianchi@studenti.polito.it';
UPDATE users SET password='66355f716a2aae17b83aa779ba491e53', salt='fb7d180cc7ea2714' WHERE email='marco.ferrari@studenti.polito.it';
UPDATE users SET password='1e2e1d9559c2e2c8904bb8bac3c30721', salt='49486b6d136767b0' WHERE email='laura.russo@studenti.polito.it';
UPDATE users SET password='ff9c065a2e63f12e54a52e64ccacb0a4', salt='5f0052e042c169c7' WHERE email='alessandro.bruno@studenti.polito.it';
UPDATE users SET password='d05aed76a376614fe3084d737f34e006', salt='9a4ff14202d1bb6c' WHERE email='francesca.romano@studenti.polito.it';
UPDATE users SET password='786be016651093bb4babfe00f776af52', salt='002522debda31846' WHERE email='davide.ricci@studenti.polito.it';
UPDATE users SET password='10f6d3836f7749cc0b4ee0fa2ac31ee2', salt='458d46eb60d21dba' WHERE email='chiara.marino@studenti.polito.it';
UPDATE users SET password='51f9fbd04b19c11736e76851fbdadc96', salt='23b810e33064328d' WHERE email='luca.greco@studenti.polito.it';
UPDATE users SET password='64fdad811cb7c1de106586b6ee9e8d58', salt='54a044f687c8dc75' WHERE email='valentina.conti@studenti.polito.it';
UPDATE users SET password='b2e278a1a7c10cbf34b46239ceaf8747', salt='ef229acaa4aa33a3' WHERE email='simone.deluca@studenti.polito.it';
UPDATE users SET password='f2809648fb3d5d956423980d3e5e5563', salt='dc94f4665a7cd723' WHERE email='elena.galli@studenti.polito.it';
UPDATE users SET password='96291ebc0d7541811ae82f59a16de424', salt='3a35d4ed3634c1a5' WHERE email='matteo.lombardi@studenti.polito.it';
UPDATE users SET password='74d9ee790ee97077604522ae3b952230', salt='83dd510c301498a6' WHERE email='sara.moretti@studenti.polito.it';
UPDATE users SET password='8e180c04f516d5aa6341b9062b0b9046', salt='1e063dc1dd40d6d5' WHERE email='andrea.barbieri@studenti.polito.it';
UPDATE users SET password='594482405f0f02d54b3646abeca1547f', salt='a5249063cdd528ad' WHERE email='martina.fontana@studenti.polito.it';
UPDATE users SET password='13105f3876a1311af1bd2068a2f8685b', salt='d43f0b813505bff0' WHERE email='riccardo.serra@studenti.polito.it';
UPDATE users SET password='a647bdeca460f516c7a04680967a4197', salt='41997cf03b6cc65a' WHERE email='federica.vitale@studenti.polito.it';
UPDATE users SET password='648527c401136cf7c01a9201e1b4b8e0', salt='a2e0ebfbe3aa9042' WHERE email='nicola.pellegrini@studenti.polito.it';
UPDATE users SET password='4f14d6215c5a336cafa4bbcb6b552ece', salt='d69d29b92fd31f70' WHERE email='roberta.caruso@studenti.polito.it';
UPDATE users SET password='5083023a7940f0bda4d94a1eefeea37b', salt='56c41aaf2173ee4b' WHERE email='stefano.fiore@studenti.polito.it';
UPDATE users SET password='84c72d14d9efae4ae83036fddf38c056', salt='33dce847983ca057' WHERE email='alessia.desantis@studenti.polito.it';
UPDATE users SET password='b531046bdbe71b54ed01ecbd3ef9510c', salt='711a0d46282ed4b2' WHERE email='emanuele.marini@studenti.polito.it';
